language: python

branches:
  only: master
sudo: false
python: 3.7

before_install:
  - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
  - export AWS_SECRETE_ACCESS_KEY=$AWS_SECRETE_ACCESS_KEY
  - python --version
env:
  global:
    -AWS_DEFAULT_REGION=us-east-1
    
install:
  - pip install awscli
  - pip install -r requirement.txt
  - export GIT_TOKEN=$GIT_TOKEN



script: 
  - aws wafv2 get-ip-set --name Test --scope REGIONAL --id e35fbeff-b614-47ed-b5e4-9b2c1bc7ee4d --region us-east-1 --query "IPSetAddresses" > test.txt
  - aws wafv2 update-ip-set --name Test --scope REGIONAL --id e35fbeff-b614-47ed-b5e4-9b2c1bc7ee4d --addresses 198.51.100.0/16 --lock-token 447e55ac-2396-4c6d-b9f9-86b67c17f8b5


after_success: 
  - aws wafv2 get-ip-set --name Test --scope REGIONAL --id e35fbeff-b614-47ed-b5e4-9b2c1bc7ee4d --region us-east-1 --query "IPSetAddresses" > test.txt
  - aws wafv2 update-ip-set --name Test --scope REGIONAL --id e35fbeff-b614-47ed-b5e4-9b2c1bc7ee4d --addresses 198.51.100.0/16 --lock-token 447e55ac-2396-4c6d-b9f9-86b67c17f8b5

# # safelist
# branches:
#   olny:
#   - master
#   - /[upt][a-q]*[t]\b//
  
# # blocklist
# branches:
#   except:
#   - opt
# # comments
  
